[workspace]
members = [
    "helloworld",
    "benchmarks",
    "primitives",
    "custom_types",
    "variable_bindings",
    "types",
    "conversion",
    "expressions",
    "flow_control",
    "functions",
    "modules"
]