version: '3.9'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: eztutor
      POSTGRES_DB: eztutor
  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
