receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

exporters:
  otlp/traces:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/metrics:
    endpoint: data-prepper:21891
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/logs:
    endpoint: data-prepper:21892
    tls:
      insecure: true
      insecure_skip_verify: true
  logging:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/traces]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/metrics]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp/logs]